"""
Sagar AI — SQLAlchemy ORM Models
Problem Statement: SIH 26176

Table design mirrors the domain model used by the frontend store:
  - Decision          (the committed plan)
  - RouteSegment      (ordered legs of a decision)
  - Dependency        (external commitments linked to segments)
  - ChangeEvent       (environmental / operational disruption)
  - RepairCandidate   (minimal-change options generated by the engine)
  - ApprovalRecord    (human-approval audit trail — immutable once written)
  - AuditEntry        (general history log for every state transition)
"""

import json
from datetime import datetime, timezone

from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
)
from sqlalchemy.orm import relationship

from app.database import Base


def _utcnow():
    return datetime.now(timezone.utc)


# ── Decision ───────────────────────────────────────────────────────────────

class Decision(Base):
    __tablename__ = "decisions"

    id = Column(String, primary_key=True)          # e.g. "DEC-2026-084"
    title = Column(String, nullable=False)
    objective = Column(Text, nullable=True)
    status = Column(String, nullable=False, default="DRAFT")
    # Allowed statuses: DRAFT | COMMITTED | IMPACTED | REPAIR_PENDING | UPDATED | SUPERSEDED
    version = Column(String, nullable=False, default="v1.0")
    officer = Column(String, nullable=True)

    departure_port = Column(String, nullable=True)
    destination_port = Column(String, nullable=True)
    total_distance_nm = Column(Float, nullable=True)
    planned_speed_kts = Column(Float, nullable=True)
    original_eta = Column(String, nullable=True)
    current_segment = Column(String, nullable=True)

    schedule = Column(Text, nullable=True)
    assumptions_json = Column(Text, nullable=True)    # JSON list
    data_source_type = Column(String, nullable=True, default="SIMULATED")
    data_quality = Column(String, nullable=True)

    created_at = Column(DateTime(timezone=True), default=_utcnow)
    committed_at = Column(DateTime(timezone=True), nullable=True)
    updated_at = Column(DateTime(timezone=True), default=_utcnow, onupdate=_utcnow)

    # Relationships
    segments = relationship("RouteSegment", back_populates="decision", cascade="all, delete-orphan", order_by="RouteSegment.order_index")
    dependencies = relationship("Dependency", back_populates="decision", cascade="all, delete-orphan")
    change_events = relationship("ChangeEvent", back_populates="decision", cascade="all, delete-orphan")
    repair_candidates = relationship("RepairCandidate", back_populates="decision", cascade="all, delete-orphan")
    approval_records = relationship("ApprovalRecord", back_populates="decision", cascade="all, delete-orphan")
    audit_entries = relationship("AuditEntry", back_populates="decision", cascade="all, delete-orphan")

    @property
    def assumptions(self):
        return json.loads(self.assumptions_json) if self.assumptions_json else []

    @assumptions.setter
    def assumptions(self, value):
        self.assumptions_json = json.dumps(value)


# ── Route Segment ─────────────────────────────────────────────────────────

class RouteSegment(Base):
    __tablename__ = "route_segments"

    id = Column(Integer, primary_key=True, autoincrement=True)
    segment_id = Column(String, nullable=False)     # "S1", "S2", …
    decision_id = Column(String, ForeignKey("decisions.id"), nullable=False)
    order_index = Column(Integer, nullable=False, default=0)
    name = Column(String, nullable=False)
    distance_nm = Column(Float, nullable=True)
    status = Column(String, nullable=False, default="UNAFFECTED")
    condition = Column(String, nullable=True)
    wave_height_m = Column(Float, nullable=True)
    wind_kts = Column(Float, nullable=True)
    details = Column(Text, nullable=True)
    start_lat = Column(Float, nullable=True)
    start_lon = Column(Float, nullable=True)
    end_lat = Column(Float, nullable=True)
    end_lon = Column(Float, nullable=True)
    repair_waypoint_lat = Column(Float, nullable=True)
    repair_waypoint_lon = Column(Float, nullable=True)

    decision = relationship("Decision", back_populates="segments")


# ── Dependency ────────────────────────────────────────────────────────────

class Dependency(Base):
    __tablename__ = "dependencies"

    id = Column(String, primary_key=True)           # "DEP-01", …
    decision_id = Column(String, ForeignKey("decisions.id"), nullable=False)
    dep_type = Column(String, nullable=True)
    name = Column(String, nullable=False)
    commitment = Column(Text, nullable=True)
    source = Column(String, nullable=True)
    condition = Column(Text, nullable=True)
    linked_segments_json = Column(Text, nullable=True)  # JSON list
    impact_level = Column(String, nullable=True)
    status = Column(String, nullable=True, default="VALID")
    description = Column(Text, nullable=True)
    mitigation_under_repair = Column(Text, nullable=True)

    decision = relationship("Decision", back_populates="dependencies")

    @property
    def linked_segments(self):
        return json.loads(self.linked_segments_json) if self.linked_segments_json else []

    @linked_segments.setter
    def linked_segments(self, value):
        self.linked_segments_json = json.dumps(value)


# ── Change Event ──────────────────────────────────────────────────────────

class ChangeEvent(Base):
    __tablename__ = "change_events"

    id = Column(String, primary_key=True)           # "EVT-SIM-2026-0914"
    decision_id = Column(String, ForeignKey("decisions.id"), nullable=False)
    event_type = Column(String, nullable=True)
    title = Column(String, nullable=False)
    severity = Column(String, nullable=False, default="HIGH")
    source = Column(String, nullable=True)
    source_type = Column(String, nullable=True, default="SIMULATED")
    observed_at = Column(String, nullable=True)
    location = Column(String, nullable=True)
    event_lat = Column(Float, nullable=True)
    event_lon = Column(Float, nullable=True)
    radius_nm = Column(Float, nullable=True)
    affected_segment_id = Column(String, nullable=True)
    description = Column(Text, nullable=True)
    quality = Column(String, nullable=True)
    source_record_id = Column(String, nullable=True)
    is_catastrophic = Column(Boolean, nullable=False, default=False)

    created_at = Column(DateTime(timezone=True), default=_utcnow)

    decision = relationship("Decision", back_populates="change_events")


# ── Repair Candidate ──────────────────────────────────────────────────────

class RepairCandidate(Base):
    __tablename__ = "repair_candidates"

    id = Column(String, primary_key=True)           # "R1", "R2", …
    decision_id = Column(String, ForeignKey("decisions.id"), nullable=False)
    tier = Column(String, nullable=False, default="ALTERNATIVE")
    title = Column(String, nullable=False)
    description = Column(Text, nullable=True)
    plan_churn = Column(Float, nullable=True)
    preservation_ratio = Column(Float, nullable=True)
    what_changes_json = Column(Text, nullable=True)
    what_remains_json = Column(Text, nullable=True)
    tradeoffs = Column(Text, nullable=True)
    feasibility = Column(String, nullable=True)
    score = Column(Integer, nullable=True)
    recommendation_reason = Column(Text, nullable=True)
    linked_event_id = Column(String, ForeignKey("change_events.id"), nullable=True)

    created_at = Column(DateTime(timezone=True), default=_utcnow)

    decision = relationship("Decision", back_populates="repair_candidates")

    @property
    def what_changes(self):
        return json.loads(self.what_changes_json) if self.what_changes_json else []

    @what_changes.setter
    def what_changes(self, value):
        self.what_changes_json = json.dumps(value)

    @property
    def what_remains_unchanged(self):
        return json.loads(self.what_remains_json) if self.what_remains_json else []

    @what_remains_unchanged.setter
    def what_remains_unchanged(self, value):
        self.what_remains_json = json.dumps(value)


# ── Approval Record (immutable audit trail) ───────────────────────────────

class ApprovalRecord(Base):
    __tablename__ = "approval_records"

    id = Column(Integer, primary_key=True, autoincrement=True)
    decision_id = Column(String, ForeignKey("decisions.id"), nullable=False)
    repair_candidate_id = Column(String, nullable=True)
    action = Column(String, nullable=False)   # APPROVED | REJECTED
    officer_name = Column(String, nullable=False)
    rationale = Column(Text, nullable=True)
    rejection_reason = Column(Text, nullable=True)
    verified_items_json = Column(Text, nullable=True)  # JSON bool list
    pre_approval_status = Column(String, nullable=True)
    post_approval_status = Column(String, nullable=True)
    decision_version_before = Column(String, nullable=True)
    decision_version_after = Column(String, nullable=True)

    created_at = Column(DateTime(timezone=True), default=_utcnow)

    decision = relationship("Decision", back_populates="approval_records")


# ── Audit Entry ───────────────────────────────────────────────────────────

class AuditEntry(Base):
    __tablename__ = "audit_entries"

    id = Column(Integer, primary_key=True, autoincrement=True)
    decision_id = Column(String, ForeignKey("decisions.id"), nullable=False)
    version = Column(String, nullable=True)
    status = Column(String, nullable=True)
    event = Column(String, nullable=False)
    summary = Column(Text, nullable=True)
    officer = Column(String, nullable=True)

    created_at = Column(DateTime(timezone=True), default=_utcnow)

    decision = relationship("Decision", back_populates="audit_entries")
